### ISSUE TITLE
Question about in-memory caching without the use of Redis

### ISSUE THREAD

**Issue by victoria-miltcheva** [arqo123/speedgoose#15]
Hi, I first wanted to say thank you for creating an alternative to https://github.com/boblauer/cachegoose that is actively maintained and has TS support.

I've got a question about the `applySpeedGooseCacheLayer` function. The [README](https://github.com/arqo123/speedgoose#about-the-project) mentions:

`It's caching on two levels. Shared - with redis. And local inside memory.`

I tried calling the `applySpeedGooseCacheLayer` function without providing a Redis URI, similarly to how the [`cachegoose`](https://github.com/boblauer/cachegoose#usage) function works:

```
import mongoose from "mongoose";
import { applySpeedGooseCacheLayer } from 'speedgoose';

// . . .

await applySpeedGooseCacheLayer(mongoose, {});
```

but I get an error stating that the `redisUri` property is required (https://github.com/arqo123/speedgoose/blob/master/src/types/types.ts#L29): 
<img width="716" alt="Screen Shot 2022-08-30 at 5 24 10 PM" src="https://user-images.githubusercontent.com/12804086/187554246-6ccac8c3-f0dd-4ca9-b16d-ac81504616e8.png">

I'm a bit confused by this because I thought that this package and its behavior was based off `cachegoose` (but this is also just an assumption I'm making). In `cachegoose`, if you don't include a Redis URL, it defaults to in-memory caching: https://github.com/boblauer/cachegoose#usage.
<img width="692" alt="Screen Shot 2022-08-30 at 5 28 57 PM" src="https://user-images.githubusercontent.com/12804086/187554781-a9b7673d-0d46-4af8-bbca-2f78c044b825.png">

My questions are:
- Is in-memory caching without the use of Redis supported by this package?
- If not, will this be part of the future roadmap?

Thank you!

**Comment by arqo123** [comment]
Hi! Thank you for using it!  @victoria-miltcheva 

The current version is mostly a 'port' of the logic for my SaaS application which is multi-clustered. That's why I've provided it with support for Redis in the first version of it. 

Generally - yes. In the roadmap, there is a point with adding support for more caching clients (like Memcached). But would be good to start implementation with "in-memory" strategy - as it will help more users :)

**Comment by victoria-miltcheva** [comment]
Hi @arqo123, I appreciate your prompt and thorough response 😄. Also, it's good to hear that this feature is generally on the roadmap.

> And just one remark... it's not based on cachegoose. The algorithms in speedgoose are quite complex. It's not just caching a key-value pairs, but also hydrated results and relations between results and records.)

Gotcha, thanks for clarifying this. I should not have made the assumption that this was based off cachegoose 😅 .

**Comment by arqo123** [comment]
@victoria-miltcheva  i've added your idea :D 

Now to make it work just install new version from NPM and set config like below:
```
applySpeedGooseCacheLayer(mongoose, {
   // as default one is REDIS, you have to set IN_MEMORY on your own
  sharedCacheStrategy : SharedCacheStrategies.IN_MEMORY
})

```

**Comment by victoria-miltcheva** [comment]
@arqo123 fantastic, thank you so much :smile:!

**Comment by NathanAP** [comment]
Sorry to revive this issue. I believe you should add this possibility to the docs. I almost gave up on using this package because it was not clear that the memory was implemented.

**Comment by zekageri** [comment]
### So i try to use it without redis

```node.js
const mongoose = require("mongoose");
//const cachegoose = require('cachegoose');
const {applySpeedGooseCacheLayer}  = require("speedgoose");

//cachegoose(mongoose);
applySpeedGooseCacheLayer(mongoose,{
    sharedCacheStrategy: SharedCacheStrategies.IN_MEMORY,
    debugConfig: {
        enabled: true,
    },
});
```

**Error:**

```
sharedCacheStrategy: SharedCacheStrategies.IN_MEMORY,   
                         ^

ReferenceError: SharedCacheStrategies is not defined        
    at Object.<anonymous>
```

Where does `SharedCacheStrategies` defined??

**Comment by zekageri** [comment]
Oh okay, never mind..

`const {applySpeedGooseCacheLayer,SharedCacheStrategies}  = require("speedgoose");`

**Comment by arqo123** [comment]
Indeed! Well done!
