### ISSUE TITLE
About some update and delete operation in the code.

### ISSUE THREAD

**Issue by YanxinNet** [arqo123/speedgoose#29]
Hello, I have a question to ask. I don't see the function of modifying or deleting the affected cache when updating records in the document and source code,
For example, when I update a document, theoretically, I should clear the cache records of the document. There is no schema in the source code The function of post ('update ', xxx).
In addition, if I use deleteMany or deleteOne to delete documents, the source code only executes schema Post ('remove ', xxx), but no schema Post ('deleteOne ', xxx), etc

**Comment by arqo123** [comment]
Hello @YanxinNet ! Thanks for using speedgoose!
If i understand you correctly you're asking for additional events for `SpeedGooseCacheAutoCleaner`? Good point! I will extend plugin auto-clear to support more events.  However I'm not sure how with actions like updateMany and deleteMany etc. I will see how much information can I find in those hooks. 
I will try to make it this week.

**Comment by YanxinNet** [comment]
> Hello @YanxinNet ! Thanks for using speedgoose! What is your current experience of using it? If i understand you correctly you're asking for additional events for `SpeedGooseCacheAutoCleaner`? Good point! I will extend plugin auto-clear ability to support more events. However, I'm not sure how with actions like updateMany and deleteMany etc. I will see how much information can I find in those hooks. I will try to make it this week.

I think your plugin is good, It make me learn more. 
To be honest, when it comes to deleteMany, I have no idea how to update the cache, so the current practice is to add a prefix of model to each cache, and when a model has new or deleted data, delete all caches related to this model.

**Comment by arqo123** [comment]
I've just finished testing of new mongoose events :) . List of currently supported events was added to readme.
