### ISSUE TITLE
cacheQuery is not a function

### ISSUE THREAD

**Issue by DecodedFinn** [arqo123/speedgoose#43]
Hello,
When I try to use the .cacheQuery function it says:
`TypeError: model.findOne(...).cacheQuery is not a function`
why do I get this error?

**Comment by arqo123** [comment]
it's probably because you've didn't apply the caching layer to the mongoose instance that you're using in your project. 

Please ensure, that you're calling it like 

```import {applySpeedGooseCacheLayer} from "speedgoose";
import mongoose from "mongoose";

applySpeedGooseCacheLayer(mongoose, {
  ...<OPTIONS HERE>
}) ```

The wrapper `applySpeedGooseCacheLayer` grabs the mongoose instance methods and is adding the cacheQuery  method to it.

**Comment by DecodedFinn** [comment]
I have added that function but it still gives me that error

**Comment by arqo123** [comment]
have you called before calling the  ` model.findOne()` function ?

Do you have two instances of mongoose somehow in your codebase?

**Comment by DecodedFinn** [comment]
I call it before model.findOne and I don't have two instances

**Comment by arqo123** [comment]
is your code in some public repo, so I can take a look at it?

**Comment by DecodedFinn** [comment]
It isn't sadly

**Comment by arqo123** [comment]
which version of mongoose are you using ? I've tested it with 5.X and 6.X

ok so for testing purposes please try the following :
Try to use cacheQuery() right after initialization of speedgoose like
```
import mongoose from 'mongoose'
import {applySpeedGooseCacheLayer} from 'speedgoose';

mongoose.connect(process.env.MONGO_URI,  {
 });

<init some model here>

applySpeedGooseCacheLayer(mongoose, {
})

const data = await mongoose.models[<yourModelName>].findOne({}).cacheQuery()
``` 
Remember, that you can also check the methods on mongoose instance etc in the debugger.  So after calling `applySpeedGooseCacheLayer` you can preview if it was properly extended.

**Comment by DecodedFinn** [comment]
I am using mongoose 6.1.5 and I tried what you told me but it still gives me it.

**Comment by arqo123** [comment]
1. What's your config for calling the applySpeedGooseCacheLayer? 
2.  Take a look at this file https://github.com/arqo123/speedgoose/blob/master/src/wrapper.ts 
as You can see there, extending the mongoose instance is the last step - so I think something might go wrong while calling the function **before** actually calling 
```
...
addCachingToQuery(mongoose)
addCachingToAggregate(mongoose)
```
So from that, you can do two things -> try to debug it straight in the node_modules by adding some console logs, or / and wrap
`applySpeedGooseCacheLayer`  with the `try catch` and check if there is some error in the logs

**Comment by DecodedFinn** [comment]
i am passing the example config so like the Redis URL nothing else

**Comment by arqo123** [comment]
So please try with in memory strategy, maybe there is some problem with connecting to redis. And how about point number 2? Have you tried it already?

**Comment by DecodedFinn** [comment]
Okay it's fixed now it was a problem with the node model folder

**Comment by arqo123** [comment]
Good to hear that!

**Comment by DecodedFinn** [comment]
yes you can
and have a nice day/night
