### ISSUE TITLE
Cache not working for in memory?

### ISSUE THREAD

**Issue by NathanAP** [arqo123/speedgoose#45]
Hello! 

I'm testing your package in my project, but it seems that I'm doing something wrong?

Every of my requests checks for the User's id that is stored in my token, something like this:

```js
const requestUser = await User.findOne({
   _id: response.locals.userAccessTokenAuthorizationData.user,
}).cacheQuery()
```

But it seems that something is wrong, because it never finds the key in the cache:
(The white log is mine, just to show that its different images and requests)

Request 1:
![image](https://user-images.githubusercontent.com/12821171/216344828-740495d4-bb6a-413d-a0c4-9c0258921afe.png)

Request 2:
![image](https://user-images.githubusercontent.com/12821171/216345619-9e7dd6f2-36a7-42f1-8158-d3853965bf87.png)

Both of them have the same key to cache:
```json
{"query":{"_id":"63bc7168da241b97ef45518b"},"collection":"users","op":"findOne","projection":{},"options":{}} 
{"query":{"_id":"63bc7168da241b97ef45518b"},"collection":"users","op":"findOne","projection":{},"options":{}}
```

Maybe I did something wrong in my configuration?

```js
applySpeedGooseCacheLayer(mongoose, {
    sharedCacheStrategy: SharedCacheStrategies.IN_MEMORY,
    debugConfig: {
        enabled: true,
    },
})
```

**Comment by arqo123** [comment]
Hello! Thank You for finding that issue. It was my fault :( The problem was with the TTL. By default, it was set to 60 -> which in the case of RedisStrategy means 60 seconds. But... for the in-memory strategy provider, it was 60ms. Now it should be fixed.

New version is 1.2.19.
Please update and check if it works.

**Comment by NathanAP** [comment]
Hello, it is! Thanks for your effort :)

**Comment by arqo123** [comment]
@NathanAP You're welcome! I would be glad if You would send me a review after tests.

**Comment by NathanAP** [comment]
I just commited the version with this library implemented.
It worked like a charm so far! I need to do a lot of testing in my frontend, but its already a good difference!

I'm not really experienced with backend, APIs and cache to tell you, can you explain me if there is any case there is not worth caching stuff? 
Also, if something is cached and then used, does it refresh the 60 seconds timer back to 0?

**Comment by arqo123** [comment]
Well with that library you can potentially cache most of your request if they are not changing rapidly. I mean if your system will perform saves on given resource with low frequency then you can cache everything. But remember to apply auto cleaning plugin to your model - it will clean data in cache, when someone change in given record appear. 

Basicly if your system is not multi-cluster based then you can cache everything - i need to make autoclearing work Mork efficient for distributed systems. 

About ttl - if the counter reach zero, cached Data is erased from cache. It will be refreshed on next call. It will not be refreshed when it hits zero. Imagine case when 1000 of cached results hit zero in the same moment... That would be bad.

**Comment by NathanAP** [comment]
> Well with that library you can potentially cache most of your request if they are not changing rapidly. I mean if your system will perform saves on given resource with low frequency then you can cache everything. But remember to apply auto cleaning plugin to your model - it will clean data in cache, when someone change in given record appear.

Yeah, I did just like in docs. It seemed to work fine, next week I'll make better tests.
Also, they were reflected in my tests and worked really well :)

> Basicly if your system is not multi-cluster based then you can cache everything - i need to make autoclearing work Mork efficient for distributed systems.

Got it! In my code I found some places that caching wasn't really relevant, but in any case, its good to know I can do everywhere.

> About ttl - if the counter reach zero, cached Data is erased from cache. It will be refreshed on next call. It will not be refreshed when it hits zero. Imagine case when 1000 of cached results hit zero in the same moment... That would be bad.

Oh no no, I mean like:

1) Request was made
2) Cache is created at 60s and starts counting down
3) Made the same request again
4) Cached data is at 40s and keeps counting down? Or refreshes back to 60s?

**Comment by arqo123** [comment]
> Oh no no, I mean like:
>Request was made
>Cache is created at 60s and starts counting down
>Made the same request again
>Cached data is reused at 40s and then keeps counting down? Or refreshes back to 60s?

So in that case for both strategies (InMemory and Redis) read operation will not reset/extend that time. 

But that might be a future improvement. Let me create an issue for that - so maybe even new contributors will do it :)
