### ISSUE TITLE
[TTL] - Auto refresh expiring time when read operation is performed. 

### ISSUE THREAD

**Issue by arqo123** [arqo123/speedgoose#47]
The current behavior of the cache will not extend expire time of the result when a read operation is performed for a given resource.
 
**Current behavior**
1. Do a query
2. Cache is created at 60s and starts counting down
3. After 20s Do the same query again
4. Cached data is reused but the expiry time was not extended - so it's 40s  now.

**TODO:**
As an option for a Query and Aggregation, would be good to create a param that can be passed next to the TTL value, to 
optionally change the behavior above to work like

1. Do a query
2. Cache is created at 60s and starts counting down
3. After 20s Do the same query again
4. Cached data is reused and expiry tam was refreshed - so it's 60s  now.

So for example it can be called like `Model.find({}).cacheQuery({ttl: 60, refreshExpiryTimeOnRead: true })`
Of course, param name might be different :) 

Acceptance criteria: 
1. Should work for both strategies
2. Should be optional 
3. Should be unit tested

**Comment by elonyavist** [comment]
Hi @arqo123, great project! I'd like to try to add this enhancement

**Comment by arqo123** [comment]
Hello @elonyavist! Sure, feel free to ask me anything below in the ticket. I would try to respond ASAP :)

**Comment by elonyavist** [comment]
Perfect!! I'm working on it :)

**Comment by arqo123** [comment]
@elonyavist  i've updated repo with husky, prettier and more linting rules. Please merge changes or rebase your code.

**Comment by elonyavist** [comment]
@arqo123 looking at the documentation (redisClient and keyv) seems doesn't exits a proper method to refresh the TTL. I think, if the use use the new parameter, we have to set again the value with the same key and the TTL

**Comment by arqo123** [comment]
@elonyavist  In the case of keyv - yes. Inside it's just a normal JS map.
But in the case of redis please just call `expire()` method on the client.

Please check how it's done here https://github.com/arqo123/speedgoose/blob/master/src/cachingStrategies/redisStrategy.ts#L30

**Comment by elonyavist** [comment]
@arqo123  I'm trying to declare this method:
`public abstract refreshTtlForCachedResult(namespace: string, key: string, ttl:number, value:CachedResult): Promise<void>;`
into the `CommonCacheStrategyAbstract` and into the `executeQueryWithCache` add something like that:
` if(context.shouldRefreshTtlOnRead){ await refreshTtlForCachedResult(context.cacheKey, context.ttl, cachedValue)}`

what do you think? 

Otherwise into the `getResultsFromCache` we have to pass `ttl` and the new `shouldRefreshTtlOnRead` params

**Comment by arqo123** [comment]
@elonyavist 

> @arqo123 I'm trying to declare this method: `public abstract refreshTtlForCachedResult(namespace: string, key: string, ttl:number, value:CachedResult): Promise<void>;` into the `CommonCacheStrategyAbstract` and into the `executeQueryWithCache` add something like that: ` if(context.shouldRefreshTtlOnRead){ await refreshTtlForCachedResult(context.cacheKey, context.ttl, cachedValue)}`
 
 Yes, that's correct :)

**Comment by elonyavist** [comment]
perfect! Thx
