### ISSUE TITLE
Bug in cleaning cache using 'SpeedGooseCacheAutoCleaner'

### ISSUE THREAD

**Issue by farrukh28** [arqo123/speedgoose#52]
So the bug is: I query documents using aggregate function and use `cachePipeline()` to cache aggregate results. But when, I create a new document in the model more specifically modify the documents, and again query the documents, I don't see the added documents. Maybe `SpeedGooseCacheAutoCleaner()` is not cleaning up when creating new docs using `MyModel.create()` method, or `cachePipeline()` has some issues.

**Comment by arqo123** [comment]
Hello @farrukh28!  Hmm in the case of `MyModel.create()` method, the cleaning logic event emitter should invoke cleaning for the whole model - which should also clean all the cached pipelines assigned to given model. Please run the library in debug mode, and check if  that debug line is triggered
https://github.com/arqo123/speedgoose/blob/1a9a3c8eedc44a3d332ac3b6c1a3a9f4951896a1/src/mongooseModelEvents.ts#L10 

If your pipeline was runner on `model X` and inside this query you're making lookups to fetch some data from `model Y`, then any saves done on `model Y` will not reset the cache for this pipeline as it was  called on `model X` .  In that case you can use `clearCachedResultsForModel()` to clear that cache manually. 

But firstly please check debug logs - you can even pass it here

**Comment by farrukh28** [comment]
@arqo123 Here is the debug log
`  speedgoose:cacheClear:cacheClear  Clearing results and hydration cache for recordId  63ea33b1d28a546669aefb9b +0ms`

**Comment by arqo123** [comment]
I will try to reproduce it then, thanks for your ticket. I just need one more thing - are you using your custom `cacheKey` here ? Also please send me your speedgoose config which you applied into the `applySpeedGooseCacheLayer()` function

**Comment by arqo123** [comment]
For me, it's working fine. I've tried to achieve the same result as You ... can you please provide me steps to reproduce?
