### ISSUE TITLE
No _id found on document! When using 'data.save() or data.deleteOne()' (only when data is already found)

### ISSUE THREAD

**Issue by dewstouh** [arqo123/speedgoose#58]
# Example steps to reproduce this error:
## Schema example
```js
const schema = new Schema({
    userId: {
        type: String,
        required: true,
        unique: true
    },
    test: {
        type: String,
    },
});
```
## Code example
```js
//Load schema
const UserSchema = require('path/to/schema');
//Find data or create it if it not exists (this works fine)
const userData = await UserSchema.findOne({userId: 123}).cacheQuery() || await new UserSchema({userId: "123"}).save();
//data is found or created, now let's say we want to update using the traditional document.save method

//when error hits
userData.test = "456"; 
await userData.save(); //MongooseError: No _id found on document!
```

Also happens when using `document.deleteOne()`

**Comment by dewstouh** [comment]
> # Example steps to reproduce this error:
> ## Schema example
> ```js
> const schema = new Schema({
>     userId: {
>         type: String,
>         required: true,
>         unique: true
>     },
>     test: {
>         type: String,
>     },
> });
> ```
> 
> ## Code example
> ```js
> //Load schema
> const UserSchema = require('path/to/schema');
> //Find data or create it if it not exists (this works fine)
> const userData = await UserSchema.findOne({userId: 123}).cacheQuery() || await new UserSchema({userId: "123"}).save();
> //data is found or created, now let's say we want to update using the traditional document.save method
> 
> //when error hits
> userData.test = "456"; 
> await userData.save(); //MongooseError: No _id found on document!
> ```
> 
> Also happens when using `document.deleteOne()`

I am using redis for caching btw

**Comment by dewstouh** [comment]
Apparently this error is because i was using an old version of mongoose, i updated it and the issue got fixed

**Comment by arqo123** [comment]
@dewstouh  Good to hear! Enjoy the plugin and hope it will speed your project up!
