### ISSUE TITLE
How to delete specific query cache

### ISSUE THREAD

**Issue by MarianoFacundoArch** [arqo123/speedgoose#65]
How to delete a specific query cache? What would be the proper way? 

 await User.find({}).cacheQuery({
      ttl: 0,
      refreshTtlOnRead: true,
    });

This works, but it's an unnecesary read itself and I don't find it pretty logic

**Comment by arqo123** [comment]
btw those options does not make any sense there.

{
ttl: 0 -> infinite,
refreshTtlOnRead: true -> reset the infinite ttl? 
}


If you want to handle clearing the cache manually, then you can pass the `cacheKey` in the cacheQuery options, and then call the clearCacheForKeys function

![image](https://github.com/arqo123/speedgoose/assets/26055043/e4a38b65-5da5-49e6-b34a-93f86ced832b)

**Comment by MarianoFacundoArch** [comment]
Let me give a little bit more of feedback here:
I will have several servers in different locations, really far one from another, so there not will be only one redis cache instance, there will be more than one.
So if a server updates a record, I need to delete the cache among all the cache instances everywhere in the world

**Comment by arqo123** [comment]
Well if you're running Redis as a replicaset - then this change should be automatically populated over all of your locations. 

So if the cache will be set on a single instance and it will be propagated to all of your servers - then the CLEAR action should remove it also from all of the locations. 

Please provide me with some more information if your architecture works differently. 

But answering your question -> currently you can't take the cacheKey under which the given resource is cached. But you can fork the method and pass a key manually - so you will have more control over it :) 

![image](https://github.com/arqo123/speedgoose/assets/26055043/75d4619d-e3ea-4617-8af9-0f5e5a4e538c)


![image](https://github.com/arqo123/speedgoose/assets/26055043/573aaead-7de4-49ad-b14a-3934015068d6)
