### ISSUE TITLE
IN-MEMORY used even for REDIS?

### ISSUE THREAD

**Issue by paul-reventwork** [arqo123/speedgoose#66]
Hey everyone and thank you for this awesome package!

I just have one question: 
Why is it, that in this line https://github.com/arqo123/speedgoose/blob/e796bc434ec48774e32ae6cbe8d4cd9c426142fb/src/wrapper.ts#L33
a IN-MEMORY Cache is initiated and used in the hydration, even if REDIS is chosen? I come across some errors because the Memory Cache returns outdated data, even if the database results are correct.

**Comment by arqo123** [comment]
Hydrated documents are the mongoose instance of documents from mongodb. 
You can't keep them inside redis as an object instance. So they have to be set in memory. The hydrated values are also not shared within your app instances.

How are you clearing the cache? Are you doing it manually? Please provide me steps to reproduce that error. If the cache clearing is handled by the speedgoose, the hydrated record should also be cleared.

**Comment by paul-reventwork** [comment]
Hey @arqo123,
Yes, I am using custom CacheQueryOptions with a custom cacheKey, which I manually remove after mutations with clearCacheForKey(key).

I was just wondering, because  after clearing a cacheKey the cached results on Redis become up-to-date, with the correct database result, but then the HydrationCache gives out an outdated, not uncleared value.
What I am doing now to solve it, is manually clearing the Cache with clearCacheForRecordId by the object's IDs, when clearing my custom cacheKeys.
Thank you for the input, and this awesome package! I hope I can contribute at time :)

And maybe one more question: is it possible to overwrite the value for RESULTS_NAMESPACE?

**Comment by paul-reventwork** [comment]
maybe you can export the "clearCacheForRecordId" in the default wrapper and notice it in the docs?

**Comment by arqo123** [comment]
it is arleady exported -> i just didn't mention it in the docs. I will add it soon :) 

https://github.com/arqo123/speedgoose/blob/master/index.ts


> I was just wondering, because after clearing a cacheKey the cached results on Redis become up-to-date, with the correct database result, but then the HydrationCache gives out an outdated, not uncleared value.

The question is - how you've been clearing that cache? with `clearCacheForKey()` ? Or by some custom code?

 


> And maybe one more question: is it possible to overwrite the value for RESULTS_NAMESPACE?

What do you mean by that? What is the use case?

**Comment by paul-reventwork** [comment]
now i am using both, so `clearCacheForKey` for my custom keys and also `clearCacheForRecordId` for the specific objects.
The use case would be to give the keys in redis a custom namespace, like for example `CACHE:${tenant}:${workspace}:${...}`, so a function would be useful, but setting a custom namespace, like only `CACHE` would also be a nice add-in.

Best regards,
Paul
