### ISSUE TITLE
[FEATURE REQUEST] A way to update cache with a mongoose query

### ISSUE THREAD

**Issue by n-xsi** [arqo123/speedgoose#67]
Context to make it easier to understand my use case:
- I have a Model that stores multiples documents with a UserID as a reference for all the docs.
- I use .find() since all the docs are stored in the same model but they have different properties except the UserID.
- If the user had data stored, .find() will return the user's stored data and later on I do some checks to filter the data as needed.
- If there was no data. The empty array is stored in the cache to avoid the database useless fetch that will add an extra 200ms with no data returned.
- Now later on when updating the data in the database for that User, The only way to update cache (as far as I know) is by doing the code I provided below.

```ts
// Clear cache from old data or empty array
await clearCacheForKey(`${message.author.id}_customEmbeds`);
// Update cache with new data
await EmbedsSchema.find({ userID: message.author.id }).sort({ embedType: 1 }).cacheQuery({ cacheKey: `${message.author.id}_customEmbeds` });
```

The code I provided does work but I don't think its an ideal way to rely on.
If there is something that already exists that can fix this please let me know.

Thanks and sorry if anything isnt clear enough. feel free to ask me anything if there is something you are unsure of.

**Comment by arqo123** [comment]
Hello there! If you're using some of mongoose methods to update your record, then the cache is cleared automatically for all cached keys in a given model.
So there is no reason to call clearCache manually.

But in your case what I could adwise, is to configure mongoose to use multitenancy on the field userID. In that case, caching for each of your "users" will be handled separately. So update of data for one of your users will not affect others.

**Comment by n-xsi** [comment]
I see. Thanks for the help everything is resolved now.

**Comment by arqo123** [comment]
Glad to hear that! So everything is fine for You now? Was the multitenancy tip helpful for You?
Please let me know :)
