### ISSUE TITLE
Add support for providing Redis client

### ISSUE THREAD

**Issue by IamSinghMohit** [arqo123/speedgoose#75]
Wouldn't it two separate instances of redis in my server. I am also using BullMQ which accepts a instance of redis client.

**Comment by arqo123** [comment]
hmm? What's the reason? What problem do you see by keeping 2 instances of redis? Of course someone can add it. But please, tell me something more about your need

**Comment by IamSinghMohit** [comment]
I don't know about it that much but keeping two redis instance will cause performance issues wouldn't it. If not then that meanse every thing is fine, you can close this. Thx for your time

**Comment by IamSinghMohit** [comment]
Btw, is there any way to cache the `countDocuments` returned result using speedgoose.

**Comment by arqo123** [comment]
1. No no, it's just another connection to redis and a few kb in ram to be reserved. so it's not that much. 
2. Abount count documents - yes. But please use the `count()` instead, as countDocuments is/will be deprecated in mongoose
