### ISSUE TITLE
Count method returns `undefined`

### ISSUE THREAD

**Issue by IamSinghMohit** [arqo123/speedgoose#76]
I am getting undefined when trying to cache the count of documents according to current query.

![Screenshot at 2024-03-06 19-27-26](https://github.com/arqo123/speedgoose/assets/121090745/d9658f4d-9b94-4f03-96ca-409cdd316482)

**Comment by IamSinghMohit** [comment]
This is only occuring when i got 0 documents. If i am getting documents more than 0 then it  is not returning `undefined`

**Comment by IamSinghMohit** [comment]
`cacheQuery` is not caching the result searched using regex. I think this is due that regex expressions cannot be stringified.Tell me if there is a genuine way to cache them.
![Screenshot at 2024-03-07 13-05-43](https://github.com/arqo123/speedgoose/assets/121090745/8ed3153d-87b9-4895-88bc-9fb8a7d2a60f)

**Comment by arqo123** [comment]
I've made a quick check and yes, that seems like a bug. Good catch with those regexp values. I will think about the way of handling them correctly. I haven't verify yet your first question. Could You split them into two issues? Or are they related?

**Comment by IamSinghMohit** [comment]
they are both different questions. 
1. There is a bug when caching `count()` it returns undefined if there is no document found in the database. If documents are in the number if greater than 0 then it will return number but in case of `0` it returns undefined.
2. Regex expression wasn't working properly with caching strategy.

**Comment by arqo123** [comment]
Please split them into two issues then. I will have a look. Good job
