### ISSUE TITLE
Regex is not working with cache layer

### ISSUE THREAD

**Issue by IamSinghMohit** [arqo123/speedgoose#77]
Regex is not working while trying to cache them using `cacheQuery` method. This could be due to reason that regex expressions cannot be stringified.

_Originally posted by @arqo123 in https://github.com/arqo123/speedgoose/issues/76#issuecomment-1985265845_

**Comment by arqo123** [comment]
Thx for the bug , fixed in  https://github.com/arqo123/speedgoose/tree/77-regex-is-not-working-with-cache-layer
