### ISSUE TITLE
Query with regex pattern returns same result every time.

### ISSUE THREAD

**Issue by IamSinghMohit** [arqo123/speedgoose#80]
When i trying out bug fix of regex, allright it is fixed but only for the first time after cache it will allways return the same result irrespective of name `string` which i will provide.
![Uploading Screenshot at 2024-03-09 13-07-39.png…]()

**Comment by arqo123** [comment]
the new version was pulbished one minute ago - 2.0.10. That one contains the fix for regexp. Closing ticket
