### ISSUE TITLE
Cache is not cleared even after a create event

### ISSUE THREAD

**Issue by IamSinghMohit** [arqo123/speedgoose#82]
When i was testing cache clearing ability in my application, yes it does shows that caches is cleared for id... 
```
  speedgoose:cacheClear:cacheClear  Clearing results and hydration cache for recordId  65ec5abfc4a6c6b8ed4e98c6 +0ms
  speedgoose:cacheClear:cacheClear  Clearing hydration cache for recordId  65ec5abfc4a6c6b8ed4e98c6 +0ms
  speedgoose:cacheClear:cacheClear  Clearing hydration cache for recordId  65ec5abfc4a6c6b8ed4e98c6 +0ms
```
But still i get same stale data not updated one.

**Comment by arqo123** [comment]
Please show me a reproducing code. What's your config for speedgoose? Are you running it as in-memory or redis?

**Comment by IamSinghMohit** [comment]
this is my speedgoose coinfiguration.
![Screenshot at 2024-03-10 10-54-52](https://github.com/arqo123/speedgoose/assets/121090745/1b4638ba-6ea6-4e74-b72e-1c1044ef0d62)
this is where i am applying speedgoose to a model.
![Screenshot at 2024-03-10 10-56-21](https://github.com/arqo123/speedgoose/assets/121090745/a47da044-d2e2-4ae4-af83-3e3489a246a7)
this is where i am using the speedgoose.
![Screenshot at 2024-03-10 10-56-47](https://github.com/arqo123/speedgoose/assets/121090745/75643825-4249-40db-8f03-cbeb7f2e40be)
this is demo video of the problem with pro

https://github.com/arqo123/speedgoose/assets/121090745/072961de-2952-4aa8-b4b6-242479564e2f

ofs.

**Comment by IamSinghMohit** [comment]
As you can already see from the video that cache is not being cleared even after a create event but it is reflected in the database that category is created.And i have alos shown you with insomania after making a get request that it is only returning the old and stale data.

**Comment by arqo123** [comment]
Ok one last thing to sum up: 
1. You're caching your list
2. Adding new element
3. So the list for whole model should be invalidated - but it's not 

My questions now are:
1. Which mongoose method are you using to add new record to the db?
2. Can You turn on debug mode and upload here the full debug log? 


The logs passed in the first comment are only for the "Hydration cache". 
I'm more interested for a log like "Clearing model cache for key' - which stands for clearing the cache for the whole model after adding/removing record.

**Comment by IamSinghMohit** [comment]
i am using mongoose transactions. 
![transaction](https://github.com/arqo123/speedgoose/assets/121090745/3b3ae8ad-7e7d-4c03-9b1c-dc147cc668d4)
mongoose version:^7.5.1

**Comment by arqo123** [comment]
Thanks! I've reproduced that. Working on fix 😎

**Comment by arqo123** [comment]
Fixed in 2.0.11, please confirm if it's working now for You :)

**Comment by IamSinghMohit** [comment]
Yes its working thx.

**Comment by arqo123** [comment]
No, im thank You for notyfing me about that!
Appreciate it @IamSinghMohit
