### ISSUE TITLE
Getting same result when using `populate` method.

### ISSUE THREAD

**Issue by IamSinghMohit** [arqo123/speedgoose#86]
I am getting same result event after quering with different id. 
```
        const cart = await CartModel.findOne({
            user_id: user.id,
            orders: req.params.id,
        })
            .populate("orders")
            .lean()
            .cacheQuery();
```
this is the first time when i am trying to query a document with a particullar id.
![Screenshot at 2024-03-19 07-09-12](https://github.com/arqo123/speedgoose/assets/121090745/85018cc1-db11-4879-8749-4376f109d5bc)

this is the second when i am trying to query a document with different id.
![Screenshot at 2024-03-19 07-08-48](https://github.com/arqo123/speedgoose/assets/121090745/a1115d88-4297-46a3-85db-f9b75aa948d1)

this is how my cart model looks  like.
![Screenshot at 2024-03-19 07-12-26](https://github.com/arqo123/speedgoose/assets/121090745/ee006fc9-5932-4b98-af63-0e96bb755f1f)

**Comment by MshObaadz** [comment]
same, but i solve this by manually set `cacheKey` instead of not passing any params

**Comment by Obaadz** [comment]
same, but i solve this by manually set `cacheKey` instead of not passing any params
