### ISSUE TITLE
cacheQuery is not a function

### ISSUE THREAD

**Issue by RaviSadam** [arqo123/speedgoose#88]
I have seen this issue [issue-43]( https://github.com/arqo123/speedgoose/issues/43)
But I am facing the same issue with in-memory strategy

```
mongoose.connect(MONGO_URL,{useNewUrlParser:true,useUnifiedTopology: true});

const user=new mongoose.Schema({
    //fields
});
user.plugin(SpeedGooseCacheAutoCleaner);

applySpeedGooseCacheLayer(mongoose,{
    sharedCacheStrategy:SharedCacheStrategies.IN_MEMORY,
    debugConfig:{
        enabled:true
    }
});


const User=new mongoose.model("speedgoose_test",user);

const result=await User.findOne({username:"ravi"}).cacheQuery();
console.log(result);

```

**Comment by arqo123** [comment]
1. Is that full code? Please check if you are uniting the mongoose at the very beginning of your app
2. Please check if you're using the same mongoose object 
3. Please share the version of speedgoose you use

**Comment by RaviSadam** [comment]
1. Yes, these is full code.(only one file)
2. Yes, same mongoose object is using.
3. Versions: mongoose: 8.5.0 sppedgoose :1.2.1 node:20.0.1

**Comment by arqo123** [comment]
please try with the latest speedgoose  which is 2.0.13

**Comment by RaviSadam** [comment]
Certainly!

**Comment by arqo123** [comment]
So? Is it working for You right now? If yes, then please close the ticket

**Comment by RaviSadam** [comment]
Yes, it's working. Thank you for your time 🪄
